GHActions: Improve failure message for prettier lint failures

diff --git a/.github/workflows/lint_gamedb.yml b/.github/workflows/lint_gamedb.yml
--- a/.github/workflows/lint_gamedb.yml
+++ b/.github/workflows/lint_gamedb.yml
@@ -35,4 +35,9 @@ jobs:
 
       - name: Check Formatting
         run: |
-          prettier --check ./bin/resources/GameIndex.yaml
+          if ! prettier --check bin/resources/GameIndex.yaml; then
+            prettier --write bin/resources/GameIndex.yaml
+            echo "Prettier failed, diff:"
+            git diff bin/resources/GameIndex.yaml
+            exit 1
+          fi
